### ISSUE TITLE
Unhandled stream error in pipe.

### ISSUE THREAD

**Issue by DaveSenn** [panuhorsmalahti/gulp-tslint#57] opened 2016-03-13 16:58 UTC
gulp-tslint throws the following error:
stream.js:74
      throw er; // Unhandled stream error in pipe.

gulp-tslint version:4.3.3
tslint version:3.6.0
Operating system: Windows 8.1

Example gulp configuration (if applicable):

`
    // ===========================================================================
    // Load gulp plug-ins ========================================================
    // ===========================================================================
    var gulp = require('gulp');
    var util = require('gulp-util');
    var debug = require('gulp-debug');
    var gulpif = require('gulp-if');
    var rename = require('gulp-rename');
    
    var sass = require('gulp-sass');
    var stripCssComments = require('gulp-strip-css-comments');
    
    var tsc = require('gulp-typescript');
    var tslint = require('gulp-tslint');
    var sourcemaps = require('gulp-sourcemaps');
    var uglify = require('gulp-uglify');
    var concat = require('gulp-concat');
    
    var tsProject = tsc.createProject('tsconfig.json');
    
    // ===========================================================================
    // Configuration =============================================================
    // ===========================================================================
    var config = {
        src: {
            root: {
                sass: 'styles/_Custom/',
                ts: 'scripts/_Custom/'
            },
            bs: 'styles/bootstrap.scss'
        },
        dest: {
            root: {
                styles: '../css/',
                scripts: '../js/'
            },
            style: {
                bs: 'bootstrap.min.css',
                mainStyle: 'site.min.css',
                mergedResult: 'Main.css'
            },
            mainScriptName: 'Main.js'
        },
        isReleaseBuild: false,
        isInWatchMode: false
    };
    
    
    //Set typescript files
    config.src.ts = [getTsPath('**/*.ts'), 'typings/tsd.d.ts'];
    
    // Gets the path for the given typescript file.
    function getTsPath(file) {
        return config.src.root.ts + file;
    }
    
    // ===========================================================================
    // Tasks =====================================================================
    // ===========================================================================
    
    gulp.task('tsLint', function () {
        return gulp.src(config.src.ts)
            .pipe(tslint())
            .pipe(tslint.report('verbose', {
                /*emitError: false*/
            }))
            .on('error', function (error) {
                util.log('TS lint failed, details:');
                util.log(error.message);
    
                if (!config.isInWatchMode)
                    return process.exit(-1);
            });
    });
    
    gulp.task('ts', ['tsLint'], function () {
        var tsResult = gulp.src(config.src.ts)
            .pipe(gulpif(!config.isReleaseBuild, sourcemaps.init()))
            .pipe(tsc(tsProject));
    
        tsResult.dts.pipe(gulp.dest(config.dest.root.scripts));
        return tsResult.js
            .pipe(concat(config.dest.mainScriptName))
            .pipe(uglify())
            .pipe(gulpif(!config.isReleaseBuild, sourcemaps.write()))
            .pipe(gulp.dest(config.dest.root.scripts));
    });
    
    // Default task, run when no arguments are specified
    gulp.task('default', ['styles', 'ts']);
`

Error console output:
[17:57:49] Using gulpfile C:\_git\HouseConcert\.Src\HouseConcert\Assets\gulpfile.js
[17:57:49] Starting 'tsLint'...
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

SyntaxError: Unexpected token ﻿
    at Object.parse (native)
    at RcFinder.loader (C:\_git\HouseConcert\.Src\HouseConcert\Assets\node_modules\rcfinder\index.js:20:17)
    at get (C:\_git\HouseConcert\.Src\HouseConcert\Assets\node_modules\rcfinder\index.js:68:18)
    at respond (C:\_git\HouseConcert\.Src\HouseConcert\Assets\node_modules\rcfinder\index.js:122:22)
    at C:\_git\HouseConcert\.Src\HouseConcert\Assets\node_modules\rcfinder\index.js:173:28
    at C:\_git\HouseConcert\.Src\HouseConcert\Assets\node_modules\rcfinder\index.js:53:7
    at FSReqWrap.oncomplete (fs.js:82:15)

TypeScript example code (if applicable):

function initialize(): void {
    console.log('hi');
}

**Comment by panuhorsmalahti** [comment] 2016-03-15 16:23
Seems like the tsconfig.json can't be parsed. Did you run it through a JSON validator?

**Comment by DaveSenn** [comment] 2016-03-19 12:17
This is my tsconfig.json file:

    {
    	"compilerOptions": {
    		"target": "es5",
    		"sourceMap": true
    	}
    }

It looks good to me and jsonlint did not report any errors.

**Comment by panuhorsmalahti** [comment] 2016-03-24 19:40
Can you add debugging to this line https://github.com/spalger/rcfinder/blob/master/index.js#L20 to see what file rcfinder is trying to parse. Verify that it's trying to load your file.

**Comment by craxal** [comment] 2016-03-30 21:22
Getting the same error here. Weird thing is I'm doing nearly the exact same thing in two different projects, and one successfully runs tslint while the other gets this error. Same tslint configuration settings, same package versions.

```javascript
var gulp = require("gulp");
var ts = require("gulp-typescript");
var tslint = require("gulp-tslint");

gulp.task("lint", function() {
    return gulp.src(["./src/**/*.ts"])
        .pipe(tslint({ configuration: require("./tslint.json") }))
        .pipe(tslint.report("prose", { emitError: false }));
});
```

**Comment by panuhorsmalahti** [comment] 2016-05-04 18:07
The latest gulp-tslint might give a better error message.

**Comment by cbruun** [comment] 2016-05-30 12:49
Are you on Windows and using Visual Studio by any chance? My issue was that Visual Studio added some hidden characters to the tslint.json file that the JSON parsing did not like.

After I created a new tslint.json file from scratch using Notepad++ it worked for me.

**Comment by timbrown81** [comment] 2016-06-24 14:03
The issue is actually with tslint.  I've reported the bug over there.  https://github.com/palantir/tslint/issues/1334

**Comment by panuhorsmalahti** [comment] 2016-07-13 17:20
Closing as likely fixed in tslint.

**Closed by panuhorsmalahti** 2016-07-13 17:20 UTC

**Comment by craxal** [comment] 2016-07-18 20:22
I've updated to the latest tools, and this problem appears to have disappeared. Whatever happened, it worked!
