### ISSUE TITLE
TypeError: undefined is not a function at Gulp

### ISSUE THREAD

**Issue by yahyaKacem** [panuhorsmalahti/gulp-tslint#59] opened 2016-03-17 16:46 UTC
gulp-tslint version: 3.6.0
tslint version: 3.6.0
Operating system: Ubuntu 14.04

Example gulp configuration (if applicable):

 ```
/*jslint maxlen:160*/
 (function (require) {
   "use strict";
   var gulp, tslint;
   gulp   = require('gulp');
   tslint = require('gulp-tslint');
   gulp.task("tslint", function() {
    return gulp.src(["src/**/*.ts"])
               .pipe(tslint())
               .pipe(tslint.reporter("verbose"));
   });
 }(require));

```

Error console output:
> [17:26:58] Using gulpfile /var/www/tests/gulp_error/gulpfile.js [17:26:58] Starting 'tslint'... [17:26:58] 'tslint' errored after 6.08 ms [17:26:58] TypeError: undefined is not a function at Gulp. (/var/www/tests/gulp_error/gulpfile.js:9:36) at module.exports (/var/www/tests/gulp_error/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7) at Gulp.Orchestrator._runTask (/var/www/tests/gulp_error/node_modules/gulp/node_modules/orchestrator/index.js:273:3) at Gulp.Orchestrator._runStep (/var/www/tests/gulp_error/node_modules/gulp/node_modules/orchestrator/index.js:214:10) at Gulp.Orchestrator.start (/var/www/tests/gulp_error/node_modules/gulp/node_modules/orchestrator/index.js:134:8) at /home/username/.nvm/versions/node/v0.12.12/lib/node_modules/gulp/bin/gulp.js:129:20 at process._tickCallback (node.js:355:11) at Function.Module.runMain (module.js:503:11) at startup (node.js:129:16) at node.js:814:3

TypeScript example code (if applicable):
https://github.com/yahyaKacem/gulp_error

**Comment by panuhorsmalahti** [comment] 2016-03-24 20:47
This error is caused by a typo in the following line:
```
.pipe(tslint.reporter("verbose"));
```

Fixed with this:
```
.pipe(tslint.report("verbose"));
```

This is documented in the readme, so closing.

**Closed by panuhorsmalahti** 2016-03-24 20:47 UTC
